# Generated by Django 5.0.2 on 2024-03-02 11:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0004_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
