# Generated by Django 5.0.2 on 2024-03-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0005_remove_post_text_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categrorie',
            field=models.CharField(blank=True, choices=[('page', 'Seite'), ('blog', 'Blog'), ('home', 'Home')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='typ',
            field=models.CharField(blank=True, choices=[('page', 'Seite'), ('blog', 'Blog'), ('home', 'Home')], max_length=20, null=True),
        ),
    ]
