# Generated by Django 5.0.2 on 2024-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0006_post_categrorie_post_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categrorie',
            field=models.CharField(blank=True, choices=[('microsoft', 'Microsoft'), ('python', 'Python'), ('django', 'Django')], max_length=50, null=True),
        ),
    ]
