# Generated by Django 5.0.2 on 2024-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0007_alter_post_categrorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categrorie',
            field=models.CharField(blank=True, choices=[('microsoft', 'Microsoft'), ('office', 'Office'), ('python', 'Python'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('boostrap', 'Bootstrap')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
