# Generated by Django 5.0.2 on 2024-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0008_alter_post_categrorie_alter_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categrorie',
            new_name='categorie',
        ),
        migrations.AlterField(
            model_name='post',
            name='typ',
            field=models.CharField(blank=True, choices=[('page', 'Seite'), ('blog', 'Blog'), ('home', 'Home'), ('template', 'Template')], max_length=20, null=True),
        ),
    ]
