# Generated by Django 5.0.2 on 2024-03-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0011_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(blank=True, choices=[('microsoft', 'Microsoft'), ('office', 'Office'), ('python', 'Python'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('boostrap', 'Bootstrap'), ('linux', 'Linux'), ('github', 'github')], max_length=50, null=True),
        ),
    ]
