# Generated by Django 5.0.2 on 2024-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0013_alter_post_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_bild',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
