# Generated by Django 5.0.3 on 2024-03-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0014_post_banner_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_bild',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
