# Generated by Django 5.0.6 on 2024-07-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0015_alter_post_banner_bild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_bild',
            field=models.ImageField(blank=True, default='uploads/default.jpg', null=True, upload_to='uploads/'),
        ),
    ]
